#!/bin/bash

export qtpath=$HOME/Qt/5.9.1/clang_64
cd ../bsnes-plus/bsnes

rm -frd ../bsnes+.app
rm -frd ../bsnes+accuracy.app
rm -frd ../bsnes+snestistics.app

if [ "$1" == "clean" ]; then
  make clean
else
  make build -j4 profile=compatibility $1 $2 $3
  make deploy profile=compatibility $1 $2 $3
fi
